# Auto-labeling configuration for pull requests

'area: skills':
  - changed-files:
    - any-glob-to-any-file:
      - 'src/JD.SemanticKernel.Extensions.Skills/**/*'

'area: hooks':
  - changed-files:
    - any-glob-to-any-file:
      - 'src/JD.SemanticKernel.Extensions.Hooks/**/*'

'area: plugins':
  - changed-files:
    - any-glob-to-any-file:
      - 'src/JD.SemanticKernel.Extensions.Plugins/**/*'

'area: meta-package':
  - changed-files:
    - any-glob-to-any-file:
      - 'src/JD.SemanticKernel.Extensions/**/*'

'area: samples':
  - changed-files:
    - any-glob-to-any-file:
      - 'samples/**/*'

'area: documentation':
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'
      - 'docs/**/*'

'area: tests':
  - changed-files:
    - any-glob-to-any-file:
      - 'tests/**/*'

'area: ci/cd':
  - changed-files:
    - any-glob-to-any-file:
      - '.github/**/*'

'dependencies':
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.csproj'
      - 'Directory.Build.props'
      - 'Directory.Packages.props'
      - 'version.json'
